### ISSUE TITLE
errors getting `scans.tsv`

### ISSUE THREAD

**Issue by yibeichan** [courtois-neuromod/hcptrt#32]
Hi, I got the following errors when trying to `datalad get` those scans.tsv

```
get(error): sub-01/ses-001/sub-01_ses-001_scans.tsv (file) [not available; (Note that these git remotes have annex-ignore set: origin)]   
```
But I don't have any problem getting other files in this repository. (I have S3 adequately set up)
I encountered the same error when trying to get `scans.tsv` from https://github.com/courtois-neuromod/anat as well.

Are there any extra setups I need to include?

Thank you!

**Comment by yibeichan** [comment]
@bpinsard helloooo, I just want to follow up on this issue. We figured things out without getting `scans.tsv` for `hcp-trt,` but we do want to know the exact scanning time/day for `friends.` I guess we can only get such information from `scans.tsv`? But we can't get it from Datalad. Are there any alternative means to get it? 
Thank youuuu!

**Comment by bpinsard** [comment]
Hi @yibeichan sorry I completely missed your issue, (do not hesitate to tag or assign me).
These files are purposely not shared, as the scan date/time are considered sensitive (this is a mechanism implemented in heudiconv).

To better understand your needs, could you please explain what do you need this information for?

We planned to strip these from the exact datetime and replace it with one relative to first session/first scan.
Of course this relative date could maybe work for studying time-dependent processes (eg. memory), but not circadian effect as the time of day would be shifted. Also, our study sampling is not designed for studying circadian effects as the scanning schedule was mostly set as a recurring slot, convenient for the participant.

Let me know what would work for you.

**Comment by yibeichan** [comment]
Thank you! We want to account for some effects raised by time intervals between sessions. In this sense, relative time would work for our purpose. How long would it take to do the stripping? I'm also happy to help with data processing for cneuromod if needed. I'll use cneuromod data a lot anyway.

**Comment by yibeichan** [comment]
@bpinsard heyyy, just wanna follow up on this. when do you plan to release the new `scans.tsv` files?

**Comment by bpinsard** [comment]
Hi @yibeichan you can try this branch https://github.com/courtois-neuromod/friends/tree/anon_scans_dates
Either `git checkout anon_scans_date` you existing install or `datalad install -s git@github.com:courtois-neuromod/friends.git@anon_scan_dates` for a new install, you should then be able to `datalad get` the `*_scans.tsv` files with a relative acquisition date.

**Comment by yibeichan** [comment]
@bpinsard I got them!! Thank you! A quick question: how did you calculate the relative time? take `sub-01`'s data as an example, `randstr rel_acq_time` in `ses-001` has
0.0, 0.0013, 0.0037, 0.0049, etc.; in `ses-002`, we have 2.958, 2.959, 2.961, etc.
Would you mind telling me what the conversion unit is? For example, what if I want to know how many days are between ses-001 and ses-066? I only want to know relative days and hours, not the exact datetime.

btw, I had some problems with 
```
datalad install -s git@github.com:courtois-neuromod/friends.git@anon_scans_dates
``` 
but 
```
datalad install --branch anon_scans_dates -s git@github.com:courtois-neuromod/friends.git
```
worked for me

**Comment by bpinsard** [comment]
The `scans.json` at the root of the dataset contains the following metadata

```
  "rel_acq_time": {
    "LongName": "Relative acquisition time",
    "Description": "Acquisition time of the particular scan, relative to the first scan of the first session, in days."
  }
```

**Comment by yibeichan** [comment]
i see i see, so 2.958 means it's almost 3 days to the first session, thank you!
